### ISSUE TITLE
Url is not valid

### ISSUE THREAD

**Issue by mbdraks** [danijelpopovic/fake-rest-api-angular-example#7]
Hi

No matter what I use as controller URL I always get 'url is not valid'.

Probably is something very stupid on my part, can you just confirm I'm doing something wrong?

- Steps to reproduce:
Create new user
Create new project
Activate project
Create controller
  Name: controller
  URL: controller
  Description: controller

**Comment by danijelpopovic** [comment]
Hi mbdraks,

You need to create in format /something/something. example: /api/product

**Comment by mbdraks** [comment]
Thanks!
